package App;

import Vistas.Apertura;
import Vistas.Articulo;
import Vistas.Caja;
import Vistas.Ciudad;
import Vistas.Cliente;
import Vistas.Compra;
import Vistas.Configuracion;
import Vistas.Deposito;
import Vistas.Empleado;
import Vistas.ExtractoCliente;
import Vistas.ExtractoProveedor;
import Vistas.FormaPago;
import Vistas.InformeArticulo;
import Vistas.InformeCiudad;
import Vistas.InformeCliente;
import Vistas.InformeDeposito;
import Vistas.InformeEmpleado;
import Vistas.InformeProveedor;
import Vistas.Linea;
import Vistas.Marca;
import Vistas.Motivo;
import Vistas.Numeracion;
import Vistas.OrdenTrabajo;
import Vistas.Pais;
import Vistas.Proveedor;
import Vistas.Servicio;
import Vistas.Timbrado;
import Vistas.TipoArticulo;
import Vistas.TipoDocumento;
import Vistas.Venta;
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Dimension;
import java.beans.PropertyVetoException;
import javax.swing.JOptionPane;

/**
 * liz
 *
 * @author Liz
 */
public class App extends javax.swing.JFrame {

    /**
     * Creates new form App
     */
    Modelos.Usuario u = new Modelos.Usuario();

    public static int ID_USUARIO;

    public App() {
        FlatLightLaf.install();
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        ID_USUARIO = Login.IDUSUARIO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInterno = new javax.swing.JDesktopPane();
        menuGlobal = new javax.swing.JMenuBar();
        menuPrincipal = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        itemMarca1 = new javax.swing.JMenuItem();
        menuCompras = new javax.swing.JMenu();
        menuComprasMantenimiento = new javax.swing.JMenu();
        itemLinea = new javax.swing.JMenuItem();
        itemMarca = new javax.swing.JMenuItem();
        itemDeposito = new javax.swing.JMenuItem();
        itemTipoArticulo = new javax.swing.JMenuItem();
        menuComprasMovimientos = new javax.swing.JMenu();
        itemCompra = new javax.swing.JMenuItem();
        menuComprasConsultas = new javax.swing.JMenu();
        itemExtractoProveedor = new javax.swing.JMenuItem();
        menuVentas = new javax.swing.JMenu();
        menuVentasMantenimiento = new javax.swing.JMenu();
        itemMotivo = new javax.swing.JMenuItem();
        itemCaja = new javax.swing.JMenuItem();
        itemFormaPago = new javax.swing.JMenuItem();
        menuVentasMovimientos = new javax.swing.JMenu();
        itemApertura = new javax.swing.JMenuItem();
        itemVenta = new javax.swing.JMenuItem();
        menuVentasConsultas = new javax.swing.JMenu();
        itemExtractoCliente = new javax.swing.JMenuItem();
        menuServicios = new javax.swing.JMenu();
        menuServicioMovimientos = new javax.swing.JMenu();
        itemOrdenTrabajo = new javax.swing.JMenuItem();
        itemServicio = new javax.swing.JMenuItem();
        menuSistemaGeneral = new javax.swing.JMenu();
        menuComprasMantenimiento1 = new javax.swing.JMenu();
        itemDeposito1 = new javax.swing.JMenuItem();
        itemTipoArticulo1 = new javax.swing.JMenuItem();
        itemPais = new javax.swing.JMenuItem();
        itemCiudad = new javax.swing.JMenuItem();
        itemCiudad1 = new javax.swing.JMenuItem();
        itemProveedor = new javax.swing.JMenuItem();
        itemTipoDocumento = new javax.swing.JMenuItem();
        itemConfiguracion = new javax.swing.JMenuItem();
        itemTimbrado = new javax.swing.JMenuItem();
        itemArticulo = new javax.swing.JMenuItem();
        itemNumeracion = new javax.swing.JMenuItem();
        itemEmpleado = new javax.swing.JMenuItem();
        menuSistemaGeneralInformes = new javax.swing.JMenu();
        itemListaCliente = new javax.swing.JMenuItem();
        itemListaProveedor = new javax.swing.JMenuItem();
        itemListaArticulo = new javax.swing.JMenuItem();
        itemListaEmpleado = new javax.swing.JMenuItem();
        itemListaCiudad = new javax.swing.JMenuItem();
        itemListaDeposito = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        panelInterno.setBackground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout panelInternoLayout = new javax.swing.GroupLayout(panelInterno);
        panelInterno.setLayout(panelInternoLayout);
        panelInternoLayout.setHorizontalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1300, Short.MAX_VALUE)
        );
        panelInternoLayout.setVerticalGroup(
            panelInternoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );

        menuPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_dashboard_layout_48px_1.png"))); // NOI18N
        menuPrincipal.setText("Principal");
        menuPrincipal.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        menuPrincipal.add(jSeparator1);

        itemMarca1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        itemMarca1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_forward_button_26px.png"))); // NOI18N
        itemMarca1.setText("Cerrar el Sistema");
        itemMarca1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMarca1ActionPerformed(evt);
            }
        });
        menuPrincipal.add(itemMarca1);

        menuGlobal.add(menuPrincipal);

        menuCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_trolley_48px.png"))); // NOI18N
        menuCompras.setText("Compras");
        menuCompras.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        menuComprasMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_add_file_26px.png"))); // NOI18N
        menuComprasMantenimiento.setText("Mantenimientos");
        menuComprasMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemLinea.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemLinea.setText("Lineas");
        itemLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLineaActionPerformed(evt);
            }
        });
        menuComprasMantenimiento.add(itemLinea);

        itemMarca.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemMarca.setText("Marcas");
        itemMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMarcaActionPerformed(evt);
            }
        });
        menuComprasMantenimiento.add(itemMarca);

        itemDeposito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemDeposito.setText("Deposito");
        itemDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDepositoActionPerformed(evt);
            }
        });
        menuComprasMantenimiento.add(itemDeposito);

        itemTipoArticulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemTipoArticulo.setText("Tipo Articulo");
        itemTipoArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipoArticuloActionPerformed(evt);
            }
        });
        menuComprasMantenimiento.add(itemTipoArticulo);

        menuCompras.add(menuComprasMantenimiento);

        menuComprasMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_system_task_26px.png"))); // NOI18N
        menuComprasMovimientos.setText("Movimientos");
        menuComprasMovimientos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemCompra.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemCompra.setText("Compras");
        itemCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCompraActionPerformed(evt);
            }
        });
        menuComprasMovimientos.add(itemCompra);

        menuCompras.add(menuComprasMovimientos);

        menuComprasConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_survey_26px.png"))); // NOI18N
        menuComprasConsultas.setText("Consultas");
        menuComprasConsultas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemExtractoProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemExtractoProveedor.setText("Extracto de Proveedor");
        itemExtractoProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExtractoProveedorActionPerformed(evt);
            }
        });
        menuComprasConsultas.add(itemExtractoProveedor);

        menuCompras.add(menuComprasConsultas);

        menuGlobal.add(menuCompras);

        menuVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_cash_register_48px.png"))); // NOI18N
        menuVentas.setText("Ventas");
        menuVentas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        menuVentasMantenimiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_add_file_26px.png"))); // NOI18N
        menuVentasMantenimiento.setText("Mantenimientos");
        menuVentasMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemMotivo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemMotivo.setText("Motivos");
        itemMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMotivoActionPerformed(evt);
            }
        });
        menuVentasMantenimiento.add(itemMotivo);

        itemCaja.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemCaja.setText("Caja");
        itemCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCajaActionPerformed(evt);
            }
        });
        menuVentasMantenimiento.add(itemCaja);

        itemFormaPago.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemFormaPago.setText("Forma Pago");
        itemFormaPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemFormaPagoActionPerformed(evt);
            }
        });
        menuVentasMantenimiento.add(itemFormaPago);

        menuVentas.add(menuVentasMantenimiento);

        menuVentasMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_system_task_26px.png"))); // NOI18N
        menuVentasMovimientos.setText("Movimientos");
        menuVentasMovimientos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemApertura.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemApertura.setText("Apertura de Cajas");
        itemApertura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAperturaActionPerformed(evt);
            }
        });
        menuVentasMovimientos.add(itemApertura);

        itemVenta.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemVenta.setText("Ventas");
        itemVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemVentaActionPerformed(evt);
            }
        });
        menuVentasMovimientos.add(itemVenta);

        menuVentas.add(menuVentasMovimientos);

        menuVentasConsultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_survey_26px.png"))); // NOI18N
        menuVentasConsultas.setText("Consultas");
        menuVentasConsultas.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemExtractoCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemExtractoCliente.setText("Extracto de Cliente");
        itemExtractoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemExtractoClienteActionPerformed(evt);
            }
        });
        menuVentasConsultas.add(itemExtractoCliente);

        menuVentas.add(menuVentasConsultas);

        menuGlobal.add(menuVentas);

        menuServicios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_report_file_48px.png"))); // NOI18N
        menuServicios.setText("Servicios");
        menuServicios.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        menuServicioMovimientos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_system_task_26px.png"))); // NOI18N
        menuServicioMovimientos.setText("Movimientos");
        menuServicioMovimientos.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemOrdenTrabajo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemOrdenTrabajo.setText("Orden de Trabajo");
        itemOrdenTrabajo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemOrdenTrabajoActionPerformed(evt);
            }
        });
        menuServicioMovimientos.add(itemOrdenTrabajo);

        itemServicio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemServicio.setText("Servicios");
        itemServicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemServicioActionPerformed(evt);
            }
        });
        menuServicioMovimientos.add(itemServicio);

        menuServicios.add(menuServicioMovimientos);

        menuGlobal.add(menuServicios);

        menuSistemaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_database_administrator_48px.png"))); // NOI18N
        menuSistemaGeneral.setText("Sistema General");
        menuSistemaGeneral.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        menuComprasMantenimiento1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_add_file_26px.png"))); // NOI18N
        menuComprasMantenimiento1.setText("Mantenimientos");
        menuComprasMantenimiento1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemDeposito1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemDeposito1.setText("Deposito");
        itemDeposito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDeposito1ActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemDeposito1);

        itemTipoArticulo1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemTipoArticulo1.setText("Tipo Articulo");
        itemTipoArticulo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipoArticulo1ActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemTipoArticulo1);

        itemPais.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemPais.setText("Pais");
        itemPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemPaisActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemPais);

        itemCiudad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemCiudad.setText("Ciudades");
        itemCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCiudadActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemCiudad);

        itemCiudad1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemCiudad1.setText("Clientes");
        itemCiudad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCiudad1ActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemCiudad1);

        itemProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemProveedor.setText("Proveedores");
        itemProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemProveedorActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemProveedor);

        itemTipoDocumento.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemTipoDocumento.setText("Tipos de Documentos");
        itemTipoDocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTipoDocumentoActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemTipoDocumento);

        itemConfiguracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemConfiguracion.setText("Configuraciones");
        itemConfiguracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConfiguracionActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemConfiguracion);

        itemTimbrado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemTimbrado.setText("Timbrados");
        itemTimbrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTimbradoActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemTimbrado);

        itemArticulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemArticulo.setText("Articulos");
        itemArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemArticuloActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemArticulo);

        itemNumeracion.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemNumeracion.setText("Numeraciónes");
        itemNumeracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNumeracionActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemNumeracion);

        itemEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemEmpleado.setText("Empleados");
        itemEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemEmpleadoActionPerformed(evt);
            }
        });
        menuComprasMantenimiento1.add(itemEmpleado);

        menuSistemaGeneral.add(menuComprasMantenimiento1);

        menuSistemaGeneralInformes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/icons8_survey_26px.png"))); // NOI18N
        menuSistemaGeneralInformes.setText("Informes");
        menuSistemaGeneralInformes.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N

        itemListaCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaCliente.setText("Lista de Clientes");
        itemListaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaClienteActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaCliente);

        itemListaProveedor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaProveedor.setText("Lista de Proveedores");
        itemListaProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaProveedorActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaProveedor);

        itemListaArticulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaArticulo.setText("Lista de Artículos");
        itemListaArticulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaArticuloActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaArticulo);

        itemListaEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaEmpleado.setText("Lista de Empleados");
        itemListaEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaEmpleadoActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaEmpleado);

        itemListaCiudad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaCiudad.setText("Lista de Ciudades");
        itemListaCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaCiudadActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaCiudad);

        itemListaDeposito.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        itemListaDeposito.setText("Lista de Depósitos");
        itemListaDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListaDepositoActionPerformed(evt);
            }
        });
        menuSistemaGeneralInformes.add(itemListaDeposito);

        menuSistemaGeneral.add(menuSistemaGeneralInformes);

        menuGlobal.add(menuSistemaGeneral);

        setJMenuBar(menuGlobal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInterno)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInterno)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemMarca1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMarca1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemMarca1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void itemLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLineaActionPerformed
        Vistas.Linea fm = new Linea();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemLineaActionPerformed

    private void itemMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMarcaActionPerformed
        Vistas.Marca fm = new Marca();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemMarcaActionPerformed

    private void itemMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMotivoActionPerformed
        Vistas.Motivo fm = new Motivo();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemMotivoActionPerformed

    private void itemDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDepositoActionPerformed
        Vistas.Deposito fm = new Deposito();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemDepositoActionPerformed

    private void itemCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCajaActionPerformed
        Vistas.Caja fm = new Caja();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCajaActionPerformed

    private void itemFormaPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemFormaPagoActionPerformed
        Vistas.FormaPago fm = new FormaPago();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemFormaPagoActionPerformed

    private void itemTipoArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipoArticuloActionPerformed
        Vistas.TipoArticulo fm = new TipoArticulo();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemTipoArticuloActionPerformed

    private void itemDeposito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDeposito1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemDeposito1ActionPerformed

    private void itemTipoArticulo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipoArticulo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemTipoArticulo1ActionPerformed

    private void itemPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemPaisActionPerformed
        Vistas.Pais fm = new Pais();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemPaisActionPerformed

    private void itemCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCiudadActionPerformed
        Vistas.Ciudad fm = new Ciudad();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCiudadActionPerformed

    private void itemCiudad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCiudad1ActionPerformed
        Vistas.Cliente fm = new Cliente();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCiudad1ActionPerformed

    private void itemProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemProveedorActionPerformed
        Vistas.Proveedor fm = new Proveedor();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemProveedorActionPerformed

    private void itemTipoDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTipoDocumentoActionPerformed
        Vistas.TipoDocumento fm = new TipoDocumento();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemTipoDocumentoActionPerformed

    private void itemConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConfiguracionActionPerformed
        Vistas.Configuracion fm = new Configuracion();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemConfiguracionActionPerformed

    private void itemTimbradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTimbradoActionPerformed
        Vistas.Timbrado fm = new Timbrado();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemTimbradoActionPerformed

    private void itemAperturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAperturaActionPerformed
        Vistas.Apertura fm = new Apertura();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemAperturaActionPerformed

    private void itemArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemArticuloActionPerformed
        Vistas.Articulo fm = new Articulo();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemArticuloActionPerformed

    private void itemNumeracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNumeracionActionPerformed
        Vistas.Numeracion fm = new Numeracion();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemNumeracionActionPerformed

    private void itemVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemVentaActionPerformed
        Vistas.Venta fm = new Venta();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemVentaActionPerformed

    private void itemOrdenTrabajoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemOrdenTrabajoActionPerformed
        Vistas.OrdenTrabajo fm = new OrdenTrabajo();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemOrdenTrabajoActionPerformed

    private void itemEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemEmpleadoActionPerformed
        Vistas.Empleado fm = new Empleado();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemEmpleadoActionPerformed

    private void itemServicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemServicioActionPerformed
        Vistas.Servicio fm = new Servicio();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemServicioActionPerformed

    private void itemCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCompraActionPerformed
        Vistas.Compra fm = new Compra();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemCompraActionPerformed

    private void itemListaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaClienteActionPerformed
        Vistas.InformeCliente fm = new InformeCliente();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaClienteActionPerformed

    private void itemListaProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaProveedorActionPerformed
        Vistas.InformeProveedor fm = new InformeProveedor();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaProveedorActionPerformed

    private void itemListaArticuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaArticuloActionPerformed
        Vistas.InformeArticulo fm = new InformeArticulo();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaArticuloActionPerformed

    private void itemListaEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaEmpleadoActionPerformed
        Vistas.InformeEmpleado fm = new InformeEmpleado();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaEmpleadoActionPerformed

    private void itemListaCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaCiudadActionPerformed
        Vistas.InformeCiudad fm = new InformeCiudad();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaCiudadActionPerformed

    private void itemListaDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListaDepositoActionPerformed
        Vistas.InformeDeposito fm = new InformeDeposito();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemListaDepositoActionPerformed

    private void itemExtractoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExtractoClienteActionPerformed
        Vistas.ExtractoCliente fm = new ExtractoCliente();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemExtractoClienteActionPerformed

    private void itemExtractoProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemExtractoProveedorActionPerformed
        Vistas.ExtractoProveedor fm = new ExtractoProveedor();
        panelInterno.add(fm);
        Dimension desktopSize = panelInterno.getSize();
        Dimension frameSize = fm.getSize();
        fm.setLocation((desktopSize.width - frameSize.width) / 2, (desktopSize.height - frameSize.height) / 2);
        try {
            fm.setSelected(true);
            fm.show();
        } catch (PropertyVetoException e) {
            JOptionPane.showMessageDialog(null, "ERROR AL ABRIR EL FORMULARIO: " + fm.getTitle(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itemExtractoProveedorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem itemApertura;
    private javax.swing.JMenuItem itemArticulo;
    private javax.swing.JMenuItem itemCaja;
    private javax.swing.JMenuItem itemCiudad;
    private javax.swing.JMenuItem itemCiudad1;
    private javax.swing.JMenuItem itemCompra;
    private javax.swing.JMenuItem itemConfiguracion;
    private javax.swing.JMenuItem itemDeposito;
    private javax.swing.JMenuItem itemDeposito1;
    private javax.swing.JMenuItem itemEmpleado;
    private javax.swing.JMenuItem itemExtractoCliente;
    private javax.swing.JMenuItem itemExtractoProveedor;
    private javax.swing.JMenuItem itemFormaPago;
    private javax.swing.JMenuItem itemLinea;
    private javax.swing.JMenuItem itemListaArticulo;
    private javax.swing.JMenuItem itemListaCiudad;
    private javax.swing.JMenuItem itemListaCliente;
    private javax.swing.JMenuItem itemListaDeposito;
    private javax.swing.JMenuItem itemListaEmpleado;
    private javax.swing.JMenuItem itemListaProveedor;
    private javax.swing.JMenuItem itemMarca;
    private javax.swing.JMenuItem itemMarca1;
    private javax.swing.JMenuItem itemMotivo;
    private javax.swing.JMenuItem itemNumeracion;
    private javax.swing.JMenuItem itemOrdenTrabajo;
    private javax.swing.JMenuItem itemPais;
    private javax.swing.JMenuItem itemProveedor;
    private javax.swing.JMenuItem itemServicio;
    private javax.swing.JMenuItem itemTimbrado;
    private javax.swing.JMenuItem itemTipoArticulo;
    private javax.swing.JMenuItem itemTipoArticulo1;
    private javax.swing.JMenuItem itemTipoDocumento;
    private javax.swing.JMenuItem itemVenta;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menuCompras;
    private javax.swing.JMenu menuComprasConsultas;
    private javax.swing.JMenu menuComprasMantenimiento;
    private javax.swing.JMenu menuComprasMantenimiento1;
    private javax.swing.JMenu menuComprasMovimientos;
    private javax.swing.JMenuBar menuGlobal;
    private javax.swing.JMenu menuPrincipal;
    private javax.swing.JMenu menuServicioMovimientos;
    private javax.swing.JMenu menuServicios;
    private javax.swing.JMenu menuSistemaGeneral;
    private javax.swing.JMenu menuSistemaGeneralInformes;
    private javax.swing.JMenu menuVentas;
    private javax.swing.JMenu menuVentasConsultas;
    private javax.swing.JMenu menuVentasMantenimiento;
    private javax.swing.JMenu menuVentasMovimientos;
    private javax.swing.JDesktopPane panelInterno;
    // End of variables declaration//GEN-END:variables
}
